### PR TITLE
Feature/udp support

### PR DESCRIPTION
**Pull request by fciaccia**
This branch allows to trigger UDP experiments. It handles the case in which a bulksize > MAX_UDP_BULKSIZE is passed, as it provokes weird bugs in the server of iperf3 versions < 3.1.3 . It also manages the test result differently.

### CODE REVIEW

**Comment by fciaccia** [comment]
This branch includes the changes in hotfix/disable-json-output

**Comment by thiezn** [comment]
Thanks again @fciaccia ! I'll take a closer look at both pull requests in the weekend

**Comment by adrienb4** [comment]
Hi guys !

This pull requests is already merge in the master branch ?
I would like to test UDP stream with iperf.

Thank

**Comment by thiezn** [comment]
Hi again @fciaccia, commit d5f597002b654723093c472ae6952c99a5158f71 from today allows you to run UDP performance tests. Check the examples/ folder or the detailed documentation for and example. 

Thanks very much for your suggestion on setting the MAX_UDP_BULKSIZE parameter. I've carried this over into the module and mentioned you in the HISTORY.

@adrienb4 The UDP feature is included in iperf3 version 0.1.3 and have now been submitted to pypi. a pip install iperf3 should give you the latest version. (append --upgrade if an older version already exists)

**Pull request closed without merging**
